BEGIN:VCARD
VERSION:2.1
N:Gump;Forrest
FN:Forrest Gump
ORG:Gump Shrimp Co.
TITLE:Shrimp Man
TEL;WORK;VOICE:(111) 555-1212
TEL;HOME;VOICE:(404) 555-1212
ADR;WORK:;;100 Waters Edge;Baytown;LA;30314;United States of America
LABEL;WORK;ENCODING=QUOTED-PRINTABLE:100 Waters Edge=0D=0ABaytown, LA 30314=0D=0AUnited States of America
ADR;HOME:;;42 Plantation St.;Baytown;LA;30314;United States of America
LABEL;HOME;ENCODING=QUOTED-PRINTABLE:42 Plantation St.=0D=0ABaytown, LA 30314=0D=0AUnited States of America
EMAIL;PREF;INTERNET:forrestgump@walladalla.com
REV:20080424T195243Z
END:VCARD
BEGIN:VCARD
VERSION:2.1
N:Fump;Gorrest
FN:Gorrest Fump
ORG:Shrump Gimp Co.
TITLE:Mimp Shan
TEL;WORK;VOICE:(404) 555-1212
TEL;HOME;VOICE:(111) 555-1212
ADR;WORK:;;999 River Edge;Sydney;NY;90210;United States of America
EMAIL;PREF;INTERNET:gorrestfump@walladalla.com
REV:30080424T195243Z
END:VCARD
